"""
Selected bootstrap uncertainty checks for the final report.

Sources acknowledged:
- Saved CSV outputs generated by the simulation scripts in this repository.
- Standard nonparametric bootstrap resampling for seed-level uncertainty summaries.

Authorship note:
- This implementation in this repository was prepared by Ameer Alhashemi.
"""

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
OUT_CSV = ROOT / "results" / "report_uncertainty_summary.csv"
BOOTSTRAP_SEED = 20260308
N_BOOT = 20_000


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def bootstrap_ci(values, stat, seed):
    arr = np.asarray(values, dtype=float)
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(arr), size=(N_BOOT, len(arr)))
    samples = arr[idx]

    if stat == "mean":
        point = float(arr.mean())
        boot = samples.mean(axis=1)
    elif stat == "median":
        point = float(np.median(arr))
        boot = np.median(samples, axis=1)
    elif stat == "prop":
        point = float(arr.mean())
        boot = samples.mean(axis=1)
    else:
        raise ValueError(f"Unknown stat: {stat}")

    lo, hi = np.quantile(boot, [0.025, 0.975])
    return point, float(lo), float(hi)


def q1_rows():
    rows = read_csv(ROOT / "results" / "q1_seed_metrics.csv")
    grouped = defaultdict(list)
    for row in rows:
        grouped[(float(row["s"]), float(row["w"]))].append(row)

    selected = [
        ("Q1 median extinction, (s,w)=(0.8,1.0)", (0.8, 1.0), "extinction_time", "median"),
        ("Q1 median extinction, (s,w)=(1.0,0.5)", (1.0, 0.5), "extinction_time", "median"),
    ]

    out = []
    for label, key, metric, stat in selected:
        vals = [float(r[metric]) for r in grouped[key]]
        point, lo, hi = bootstrap_ci(vals, stat, BOOTSTRAP_SEED + int(100 * key[0] + 10 * key[1]))
        out.append(
            {
                "label": label,
                "estimate": point,
                "ci_low": lo,
                "ci_high": hi,
                "n_seeds": len(vals),
                "statistic": stat,
            }
        )
    return out


def q2_rows():
    rows = read_csv(ROOT / "results_q2" / "q2_summary.csv")
    selected = [
        ("Q2 mean late d", "late_distance_mean", "mean"),
        ("Q2 mean near-edge fraction", "near_edge_fraction", "mean"),
    ]

    out = []
    for i, (label, metric, stat) in enumerate(selected):
        vals = [float(r[metric]) for r in rows]
        point, lo, hi = bootstrap_ci(vals, stat, BOOTSTRAP_SEED + 1000 + i)
        out.append(
            {
                "label": label,
                "estimate": point,
                "ci_low": lo,
                "ci_high": hi,
                "n_seeds": len(vals),
                "statistic": stat,
            }
        )
    return out


def q3_rows():
    out = []

    lattice = read_csv(ROOT / "results_q3" / "lattice_summary.csv")
    vals = [float(r["late_distance_mean"]) for r in lattice]
    point, lo, hi = bootstrap_ci(vals, "mean", BOOTSTRAP_SEED + 2000)
    out.append(
        {
            "label": "Q3 lattice mean late d",
            "estimate": point,
            "ci_low": lo,
            "ci_high": hi,
            "n_seeds": len(vals),
            "statistic": "mean",
        }
    )

    small_world = read_csv(ROOT / "results_q3_sw" / "q3_sw_summary.csv")
    grouped = defaultdict(list)
    for row in small_world:
        grouped[float(row["beta"])].append(row)

    for i, beta in enumerate([0.0, 0.5]):
        vals = [float(r["late_distance_mean"]) for r in grouped[beta]]
        point, lo, hi = bootstrap_ci(vals, "mean", BOOTSTRAP_SEED + 3000 + i)
        out.append(
            {
                "label": f"Q3 small-world mean late d, beta={beta:.1f}",
                "estimate": point,
                "ci_low": lo,
                "ci_high": hi,
                "n_seeds": len(vals),
                "statistic": "mean",
            }
        )

    return out


def main():
    rows = q1_rows() + q2_rows() + q3_rows()
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["label", "estimate", "ci_low", "ci_high", "n_seeds", "statistic"],
        )
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved: {OUT_CSV}")


if __name__ == "__main__":
    main()
